// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type HealthResponse struct {
	Status string `json:"status"`
}

type PermissionInput struct {
	Action       string `json:"action"`
	ResourceType string `json:"resourceType"`
	ResourceID   string `json:"resourceId"`
	TenantID     string `json:"tenantId"`
}

type PermissionResponse struct {
	Allowed bool    `json:"allowed"`
	Error   *string `json:"error,omitempty"`
}

type Query struct {
}

type VersionResponse struct {
	Version string `json:"version"`
}
