package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"authz-service/internal/utils"
	"authz-service/pkg/logger"
	"context"
	"fmt"
)

// CheckPermission is the resolver for the checkPermission field.
func (r *mutationResolver) CheckPermission(ctx context.Context, input PermissionInput) (*PermissionResponse, error) {
	// Get user ID from context (set by auth middleware)
	userID, exists := ctx.Value("userID").(string)
	if !exists {
		logger.LogError("User ID not found in context during permission check")
		return &PermissionResponse{
			Allowed: false,
			Error:   utils.Ptr("User ID not found in context"),
		}, nil
	}

	// Set default value for resourceId if it's nil
	resourceID := ""
	if input.ResourceID != nil {
		resourceID = *input.ResourceID
	}

	// Log the permission check request
	logger.LogInfo("GraphQL permission check request",
		"user_id", userID,
		"action", input.Action,
		"resource_type", input.ResourceType,
		"resource_id", resourceID,
	)

	// Check permission
	allowed, err := r.permitService.Check(ctx, userID, input.Action, input.ResourceType, resourceID)
	if err != nil {
		logger.LogError("Failed to check permissions", "error", err)
		return &PermissionResponse{
			Allowed: false,
			Error:   utils.Ptr(fmt.Sprintf("Failed to check permissions: %s", err.Error())),
		}, nil
	}

	// Return result
	return &PermissionResponse{
		Allowed: allowed,
		Error:   utils.Ptr(""),
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthResponse, error) {
	return &HealthResponse{Status: "ok"}, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (*VersionResponse, error) {
	return &VersionResponse{Version: r.version}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
